# ========================
# APPLICATION
# ========================
spring.application.name=n8n-backend
server.port=8080

# ========================
# DATABASE (MySQL)
# ========================
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:n8n}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.archive.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_ARCHIVE_NAME:n8n_archive}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.archive.username=${DB_USER:root}
spring.datasource.archive.password=${DB_PASSWORD:root}
spring.datasource.archive.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false
spring.jpa.archive.hibernate.ddl-auto=update
spring.jpa.archive.database-platform=org.hibernate.dialect.MySQLDialect

# ========================
# LOGGING
# ========================
logging.level.com.majd.n8n=INFO
logging.level.org.hibernate.SQL=ERROR
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=ERROR

# ========================
# FILE UPLOAD
# ========================
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
